spring:
  application:
    name: eureka-server
server:
  port: 1113
eureka:
  instance:
    # 在etc文件夹下的host文件做了映射
    hostname: eurekaServerB
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaA:1112/eureka