spring:
  application:
    name: eureka-server
server:
  port: 1112
eureka:
  instance:
    # 在etc文件夹下的host文件做了映射
    hostname: eurekaServerA
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 填写注册中心的地址，多个用逗号隔开
      defaultZone: http://eurekaB:1113/eureka